version: '3.7'

services: 
  frontend:
    image: frontend-react
    build:
      context: Front/be-travelic/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443" 

    volumes:
      - /home/ubuntu/docker-volume/ssl:/var/www/html
    container_name: "frontend"
  
  backend:
    image: backend-spring
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"  


    volumes:
      - /home/ubuntu/docker-volume/ssl:/root
    container_name: "backend"
